version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '00:00'
      timezone: 'Asia/Tokyo' # 12am Central Time
    commit-message:
      prefix: '[DEPENDABOT]'
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 10
    reviewers:
      - 'jiyuujin'
    versioning-strategy: 'increase'
